apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: adservice-hpa
  namespace: default  # Change if needed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: adservice-deployment
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 2  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Target CPU utilization percentage
