apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redis-cart-hpa
  namespace: msrv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-cart-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
