apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-deployment
  namespace: msrv
  labels:
    app: cartservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice-container
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.2
          ports:
            - containerPort: 7070
          envFrom:
            - configMapRef:
                name: cartservice-env-config
