apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-deployment
  namespace: msrv
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: emailservice-container
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: emailservice-env-config
