apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice-deployment
  namespace: msrv
  labels:
    app: productcatalogservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: productcatalogservice-container
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.2
          ports:
            - containerPort: 3550
          envFrom:
            - configMapRef:
                name: productcatalogservice-env-config
