apiVersion: v1
kind: Service
metadata:
  name: adservice-service
  namespace: msrv  # Change if needed
spec:
  selector:
    app: adservice
  ports:
    - name: grpc      
      port: 9555        # Port exposed inside the cluster
      targetPort: 9555  # Port exposed by your app
  type: ClusterIP
