apiVersion: v1
kind: Service
metadata:
  name: cartservice-service
  namespace: msrv
  labels:
    app: cartservice
spec:
  selector:
    app: cartservice
  ports:
    - name: grpc    
      port: 7070        # Service port
      targetPort: 7070  # Target container port
  type: ClusterIP
