apiVersion: v1
kind: Service
metadata:
  name: checkoutservice-service
  namespace: msrv
  labels:
    app: checkoutservice
spec:
  selector:
    app: checkoutservice
  ports:
    - name: grpc
      port: 5050       # Service port
      targetPort: 5050 # Target container port
  type: ClusterIP
