apiVersion: v1
kind: Service
metadata:
  name: currencyservice-service
  namespace: msrv  # Change if needed
spec:
  selector:
    app: currencyservice
  ports:
    - name: grpc
      port: 7000      # Port exposed inside the cluster
      targetPort: 7000  # Port exposed by your app
  type: ClusterIP
