apiVersion: v1
kind: Service
metadata:
  name: emailservice-service
  namespace: msrv
  labels:
    app: emailservice
spec:
  selector:
    app: emailservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
