apiVersion: v1
kind: Service
metadata:
  name: emailservice-service
  namespace: msrv
  labels:
    app: emailservice
spec:
  selector:
    app: emailservice
  ports:
    - name: grpc
      port: 5000
      targetPort: 8080
  type: ClusterIP
