apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: msrv
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80       # Service port
      targetPort: 8080 # Target container port
  type: ClusterIP
