apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: msrv
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080       # Service port
      targetPort: 8080 # Target container port
      nodePort: 30080  # NodePort (optional; Kubernetes assigns one if not specified)
  type: NodePort
