apiVersion: v1
kind: Service
metadata:
  name: loadgenerator-service
  namespace: msrv
  labels:
    app: loadgenerator
spec:
  selector:
    app: loadgenerator
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 80   # Target container port
      nodePort: 30080  # Fixed NodePort (optional)
  type: NodePort
