apiVersion: v1
kind: Service
metadata:
  name: paymentservice-service
  namespace: msrv
  labels:
    app: paymentservice
spec:
  selector:
    app: paymentservice
  ports:
    - name: grpc
      port: 50051       # Service port
      targetPort: 50051 # Target container port
  type: ClusterIP
