apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice-service
  namespace: msrv
  labels:
    app: productcatalogservice
spec:
  selector:
    app: productcatalogservice
  ports:
    - name: grpc
      port: 3550        # Service port
      targetPort: 3550  # Target container port
  type: ClusterIP
