apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice-service
  namespace: msrv
  labels:
    app: productcatalogservice
spec:
  selector:
    app: productcatalogservice
  ports:
    - protocol: TCP
      port: 3550        # Service port
      targetPort: 3550  # Target container port
      nodePort: 30050   # Fixed NodePort (optional)
  type: NodePort
