apiVersion: v1
kind: Service
metadata:
  name: recommendationservice-service
  namespace: msrv
  labels:
    app: recommendationservice
spec:
  selector:
    app: recommendationservice
  ports:
    - name: grpc
      port: 8080       # Service port
      targetPort: 8080 # Target container port
  type: ClusterIP
