apiVersion: v1
kind: Service
metadata:
  name: redis-cart-service
  namespace: msrv
  labels:
    app: redis-cart
spec:
  selector:
    app: redis-cart
  ports:
    - name: grpc
      port: 6379        # Service port
      targetPort: 6379  # Target container port
  type: ClusterIP
