apiVersion: v1
kind: Service
metadata:
  name: shippingservice-service
  namespace: msrv  # Change if needed
spec:
  selector:
    app: shippingservice
  ports:
    - name: grpc
      port: 80      # Port exposed inside the cluster
      targetPort: 50051  # Port exposed by your app
  type: ClusterIP
