apiVersion: v1
kind: Service
metadata:
  name: shippingservice-service
  namespace: msrv  # Change if needed
spec:
  selector:
    app: shippingservice
  ports:
    - protocol: TCP
      port: 80      # Port exposed inside the cluster
      targetPort: 50051  # Port exposed by your app
      nodePort: 30008  # NodePort range (typically 30000-32767)
  type: NodePort
